In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LinearRegression as lr
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
#loading the dataset
df = pd.read_csv('ds_salaries (ML).csv')
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M
...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
3751,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
3752,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
3753,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
3754,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

In [3]:
#Handle Null Values
df.dropna(inplace=True)

In [4]:
#Data Preprocessing
# a. Handle Duplicate Records
df.drop_duplicates(inplace=True)

In [7]:
# Select x and y
X = df.drop('salary_in_usd',axis=1)
y = df['salary_in_usd']

In [14]:
enc=OrdinalEncoder()

In [15]:
X=enc.fit_transform(X)

In [16]:
# Split data into training and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [17]:
# Apply the ANN Classification model on the training dataset
linreg=lr()
linreg.fit(X_train,y_train)

LinearRegression()

In [18]:
# Generate the predicted value for the test dataset
pred = linreg.predict(X_test)
pred

array([130189.49282932, 181073.43410416, 198351.30158007,  34819.03537475,
        39369.37461096,  55471.3665022 , 120674.20361699, 144058.80643693,
        83939.0472618 , 134852.59545459, 132528.4566849 , 192296.95763293,
       148516.94622313, 103036.93025255, 196357.94564081, 162573.87686287,
       116979.10871187, 110731.98576453, 151571.8289768 , 212640.23328228,
       118582.03697507,  85400.03763982, 201440.08740988,  32690.75591773,
       139015.38900995,  48780.69146697, 127468.13701301, 148246.48767325,
       195615.55836105,  65065.01866455, 227666.81397278, 129900.01008598,
       117843.87108537, 158475.29646832, 102529.12761337, 115358.43521327,
       102072.30623258, 176330.21446459, 229122.70307145, 176144.97362244,
        50181.76155631, 224743.0797384 ,  49649.19235268, 207691.93433888,
       194165.33103754,  90431.5357273 ,  84782.32015343,  36482.75172866,
       163317.3782847 , 114848.26557145, 215289.64033165, 198319.94059786,
       116964.31679189, 104019.56400729,  52034.43372891, 127538.55156534,
       143552.15020256, 110437.14485382, 154209.03824163, 186535.19935726,
       195072.66773203, 154143.22423592, 146318.70081677,  39560.16234128,
       193561.86697038,  73972.19123872, 158827.13812525, 111165.21070393,
       127936.38017602, 215736.34146041, 200967.92408805, 198562.11980298,
       119406.40247881,  76468.97519019, 120649.13893404, 140187.64493979,
        98910.03288897,  86203.31019021, 122965.18161224, 207960.60178612,
       108635.39202904, 172232.01482175, 109900.30136648, 203515.09330098,
       198475.31704813,  89258.05732217, 100841.9982304 , 193924.11889901,
       166354.23523633, 186238.67094125, 142085.00894596, 152053.78101359,
       225422.83794533,  78782.42763807,  34617.64454053, 109163.70950286,
        67047.08768063,  48428.06462541,  40627.28706558, 116601.13463014,
       131611.68652524,  82594.72862369, 191931.76483494, 103778.13309733,
       165250.32953455,  57823.15149557, 151680.49797157,  61939.19013775,
       135356.74930829,  98970.24488261, 191626.24086588,  91869.94357848,
        52051.0537899 , 146998.76059412, 151627.66850655, 175536.22605055,
       221992.76931332, 228495.79640683, 172724.13179295, 140044.41544154,
       133145.90815161, 139542.92651348, 160843.58139789, 162723.02190869,
       172215.13413385,  51429.54631647, 100841.15827094, 159296.39647774,
       203508.88453177,  95140.13396223,  52401.8821034 , 228363.26195265,
       159662.59115091,  93620.9714988 , 109419.5456942 ,  75164.27096605,
       140594.50657899, 110344.11069452,  79431.29215211, 193879.14978133,
        99592.38132623,  54050.71777034,  45778.28931193, 112410.99042325,
       216146.8361374 , 105243.76875443, 137514.59676665,  95696.41360253,
       227694.5348591 ,  99088.47073807,  83256.27455196, 212315.90193963,
       175276.12335006, 153669.61773222,  62049.17138691,  96750.90702578,
       192001.62423684, 159372.10322438, 144617.78539463, 201160.7036279 ,
       204584.61841887, 137239.14759287,  68674.44439111, 188318.8307136 ,
       120221.95448413, 181326.68579061, 211579.31575882, 201628.4012135 ,
       205844.76567166, 160496.67486431,  67820.81680129,  21293.04731042,
       196265.29223321, 228981.61707876, 181221.49166013,  99407.36001416,
       199385.62020598, 149022.92013539,  72046.87101522, 142242.29330444,
       110950.64878779, 146490.0187448 , 179715.78931879,  63919.0372886 ,
        21447.86360461, 166182.9173083 , 143903.39042919, 206612.55457584,
       197508.02868844, 171008.82066722, 133298.2323085 ,  50030.10306951,
        75310.41225773,  91224.2833608 ,  47611.49041834, 124237.74483508,
       114111.11782053, 113649.7165478 , 119552.58975085, 206898.85678619,
       182000.13360088, 173494.90106329, 110353.78422179, 114467.82174507,
       131636.75120818,  34468.99847598,  45804.3409355 ,  52426.27214921,
        32458.07004062, 141101.39835681, 120006.04843814, 185016.21967246,
        48034.60556049, 144468.94191923, 183059.51690974,  56074.32373105,
       224039.76379258,   6671.88985692,  88510.89688685,  32419.14268116,
       209437.86463932, 116549.68508998, 146368.96212877, 181141.33760747,
       110402.00433489,  59775.77196707, 116534.0586033 , 175159.76284563,
       203922.33698254, 213663.08074961, 184105.42402923, 126845.82572168,
       194257.41729713, 163296.11626384,  53725.73777217,  28909.09569985,
       145191.84051694, 191458.931175  ,  90998.4994163 , 109433.31505128,
       155378.33639769, 127323.48395558, 159139.11211926, 136970.69418597,
       126288.37941023, 178599.01957763, 164682.42663541, 135379.8603224 ,
        63345.3938276 , 190151.56376889, 134931.92654944, 162205.39352978,
       210007.97701708, 145311.91324045, 179374.7037446 , 197951.83801647,
        48866.53559933, 164710.14752173, 104373.6777015 , 175905.68621805,
       178924.66409036, 131890.70982186, 137936.23321247, 103595.03576075,
       182022.3064831 ,  91240.02050293, 131311.10669546, 194363.6788402 ,
       135123.65895249,  35088.66037625, 195501.6890452 ,  32598.26210945,
        45440.23975374,  39211.75669214, 180285.56536089, 143336.93457943,
       122032.5146572 , 213898.3162108 ,  30586.84643082, 134238.02724288,
       203583.65886005, 106102.68155342, 196329.92318409, 105006.13237022,
       203919.37920876, 137214.01693687, 101718.46549367, 152832.4889274 ,
        50392.44807093, 153722.46927454, 211508.83523343,  53885.57343939,
       209955.49301822, 119997.88766346, 118265.50753119,  23369.51582045,
       204959.54740918, 152129.25922099,  35418.56603129, 102687.13191824,
       114723.39031423, 214770.96914528,  44823.12765784,  77113.20926747,
       174011.21401261, 198445.75929855, 148387.38275097,  95940.9487852 ,
        26952.76835366, 149677.42274442,  53102.10473822, 203736.58344258,
       180074.74713799, 130158.1318471 ,  53434.04555022,  90688.12219557,
       177999.85800294, 135949.10759942, 162810.12731219, 199517.3271837 ,
       211050.55428707, 207892.6767258 ,  84792.1693748 , 155858.67396034,
       175793.75172896, 215514.38146868,  81158.54252567,  84448.47143323,
        66584.00484359, 217568.07612428, 136213.71657479, 136885.03389866,
       151164.92971333,  56602.6600593 , 125098.49449732, 109932.11884128,
        50479.25190402, 186843.10315324, 195743.81677618, 121799.75209133,
        55734.81957643, 125433.32711004,  47090.81386421, 201789.02409747,
        37825.57526019, 231700.08109435, 207721.76110648, 206636.70678619,
       218194.74719155, 207681.8585029 , 216675.60628513,  22764.71916619,
       213476.67976499, 112650.12744252, 180682.66723342, 158003.76625397,
        52459.18390878,  69310.79223639, 202886.39051134, 206031.96589616,
       122428.33812491, 187672.45313076, 203535.82346663,  98091.58908293,
        45092.54648234, 121239.13553411, 179819.76795771, 141587.6657535 ,
       154447.57735086, 152583.97472049,  85045.9239456 , 175866.63264793,
        70998.76452333, 171137.21911691,  46830.71116372,  26712.24453934,
       215256.25970755, 154891.38667889,  43319.7539675 , 219497.75482171,
        51034.75711338,  46232.74860165,  60060.79565141, 191783.95289033,
       136628.86580636, 208967.98544515, 213316.01925675,  53651.37962137,
       105770.74074142, 123641.52931356,  22494.74472674,  36405.9577585 ,
       205578.50567611, 120124.77324464, 120576.25801507, 172929.40201175,
       186607.73585814, 120278.14455193, 185817.03449543, 202726.21435214,
       183001.07160269, 149571.03733767, 218332.70605249, 215509.1091348 ,
       118258.30037056, 129206.00718208, 159979.87396186, 173707.7423821 ,
        21950.04458974, 184519.78734136, 189535.96823106, 176729.67802819,
       141650.42642044, 167004.01731771,  44085.49670017, 128820.78831544,
        45709.88704168,  40228.61324609,  85253.85036778, 141798.48397641,
        91767.0423957 , 132470.58590356,  60862.87869093,  97367.9400048 ,
        55493.57261601, 156207.23965045, 232416.93920257, 200911.51417058,
       125079.21341583, 102836.69202559,  48792.70612076, 213704.3786758 ,
       148030.37725603, 143392.67792247, 189797.89679944, 199043.14076597,
       134588.20632889,  55685.07652584, 199351.85883018, 157685.55744112,
       144300.58176498, 102267.60135371,  54419.62808846, 130213.3692841 ,
        93358.27856799, 142704.51753498,  68783.52723243, 127710.31621813,
       115378.68336135, 228031.70189236, 103451.74028944, 133657.79998957,
       177994.58736564, 147500.46356253, 166469.50825091, 194633.30156484,
        11020.41125896,  96618.75332331,  15221.99975929, 148013.49656813,
        85965.30816571,  58310.88713382,  67811.62761999, 145129.11747427,
       218536.31711477,  90542.93488333, 145739.39926078, 147119.88318321,
       212380.13058179, 161520.1532918 , 185156.55736998, 167187.1146543 ,
       157492.66271359,  83423.28943317,  30884.21690212, 115192.92982139,
       209837.32820292, 193938.04181313,  36603.32288759,  57371.6223091 ,
       188504.51828051, 175073.6035708 ,  80352.20282396, 153787.40179582,
       186575.70671955, 116373.02603294,  89202.53862043, 145033.95301764,
       174199.8593533 ,  58242.07698712, 201064.21759155, 117911.39383697,
       150185.86302332, 106687.42212786,  74901.38022746, 149864.51231349,
       159193.66723415,  36987.23508732, 140701.93479321, 184075.04693954,
       224135.75572567,  60528.0444817 , 228795.92951186, 106013.22151695,
       156091.66506546,  64728.08722865,  75906.69277046, 102265.49547242,
       164617.42814107,  87861.705378  , 105427.76881604,  26756.19502109,
       179534.94587687, 227230.88706939,  56152.61917373,  58164.69986179,
        70496.37042862])

In [19]:
# Compute Classification metrics â€“ confusion Matrix, classification Report
mse = mean_squared_error(y_test,pred)
rmse=mse**0.5
r2=r2_score(y_test,pred)

In [20]:
print("Mean Squared Error:",mse)
print("Root Mean Squared Error:", rmse)
print("R-Squared Score:",r2)

Mean Squared Error: 1561755341.4678059
Root Mean Squared Error: 39519.05036141185
R-Squared Score: 0.6658396604467256

In [22]:
# Report the ANN model accuracy
print("ANN Model Accuracy:", linreg.score(X_test, y_test))

ANN Model Accuracy: 0.6658396604467256